function geomap(){       
    var map = new Datamap({
        element: document.getElementById('container'),
        scope: 'world',
        //fills: {
        //    defaultFill: 'cornflowerblue' // Any hex, color name or rgb/rgba value
        //},
        geographyConfig: {
           highlightOnHover: false,
           popupOnHover: false
        },
        fills: {
            'ABW': '#6baed6',
            'AFG': '#9467bd',
            'AGO': '#ff7f0e',
            'AIA': '#6baed6',
            'ALA': '#2ca02c',
            'ALB': '#2ca02c',
            'AND': '#2ca02c',
            'ARE': '#9467bd',
            'ARG': '#e377c2',
            'ARM': '#9467bd',
            'ASM': '#8c564b',
            'ATA': '#d62728',
            'ATF': '#d62728',
            'ATG': '#6baed6',
            'AUS': '#8c564b',
            'AUT': '#2ca02c',
            'AZE': '#9467bd',
            'BDI': '#ff7f0e',
            'BEL': '#2ca02c',
            'BEN': '#ff7f0e',
            'BES': '#e377c2',
            'BFA': '#ff7f0e',
            'BGD': '#9467bd',
            'BGR': '#2ca02c',
            'BHR': '#9467bd',
            'BHS': '#6baed6',
            'BIH': '#2ca02c',
            'BLM': '#e377c2',
            'BLR': '#2ca02c',
            'BLZ': '#6baed6',
            'BMU': '#6baed6',
            'BOL': '#e377c2',
            'BRA': '#e377c2',
            'BRB': '#6baed6',
            'BRN': '#9467bd',
            'BTN': '#9467bd',
            'BVT': '#d62728',
            'BWA': '#ff7f0e',
            'CAF': '#ff7f0e',
            'CAN': '#6baed6',
            'CCK': '#9467bd',
            'CHE': '#2ca02c',
            'CHL': '#e377c2',
            'CHN': '#9467bd',
            'CIV': '#ff7f0e',
            'CMR': '#ff7f0e',
            'COD': '#ff7f0e',
            'COG': '#ff7f0e',
            'COK': '#8c564b',
            'COL': '#e377c2',
            'COM': '#ff7f0e',
            'CPV': '#ff7f0e',
            'CRI': '#6baed6',
            'CUB': '#6baed6',
            'CUW': '#e377c2',
            'CXR': '#9467bd',
            'CYM': '#6baed6',
            'CYP': '#9467bd',
            'CZE': '#2ca02c',
            'DEU': '#2ca02c',
            'DJI': '#ff7f0e',
            'DMA': '#6baed6',
            'DNK': '#2ca02c',
            'DOM': '#6baed6',
            'DZA': '#ff7f0e',
            'ECU': '#e377c2',
            'EGY': '#ff7f0e',
            'ERI': '#ff7f0e',
            'ESH': '#ff7f0e',
            'ESP': '#2ca02c',
            'EST': '#2ca02c',
            'ETH': '#ff7f0e',
            'FIN': '#2ca02c',
            'FJI': '#8c564b',
            'FLK': '#e377c2',
            'FRA': '#2ca02c',
            'FRO': '#2ca02c',
            'FSM': '#8c564b',
            'GAB': '#ff7f0e',
            'GBR': '#2ca02c',
            'GEO': '#9467bd',
            'GGY': '#2ca02c',
            'GHA': '#ff7f0e',
            'GIB': '#2ca02c',
            'GIN': '#ff7f0e',
            'GLP': '#6baed6',
            'GMB': '#ff7f0e',
            'GNB': '#ff7f0e',
            'GNQ': '#ff7f0e',
            'GRC': '#2ca02c',
            'GRD': '#6baed6',
            'GRL': '#6baed6',
            'GTM': '#6baed6',
            'GUF': '#e377c2',
            'GUM': '#8c564b',
            'GUY': '#e377c2',
            'HKG': '#9467bd',
            'HMD': '#d62728',
            'HND': '#6baed6',
            'HRV': '#2ca02c',
            'HTI': '#6baed6',
            'HUN': '#2ca02c',
            'IDN': '#9467bd',
            'IMN': '#2ca02c',
            'IND': '#9467bd',
            'IOT': '#9467bd',
            'IRL': '#2ca02c',
            'IRN': '#9467bd',
            'IRQ': '#9467bd',
            'ISL': '#2ca02c',
            'ISR': '#9467bd',
            'ITA': '#2ca02c',
            'JAM': '#6baed6',
            'JEY': '#2ca02c',
            'JOR': '#9467bd',
            'JPN': '#9467bd',
            'KAZ': '#9467bd',
            'KEN': '#ff7f0e',
            'KGZ': '#9467bd',
            'KHM': '#9467bd',
            'KIR': '#8c564b',
            'KNA': '#6baed6',
            'KOR': '#9467bd',
            'KWT': '#9467bd',
            'LAO': '#9467bd',
            'LBN': '#9467bd',
            'LBR': '#ff7f0e',
            'LBY': '#ff7f0e',
            'LCA': '#6baed6',
            'LIE': '#2ca02c',
            'LKA': '#9467bd',
            'LSO': '#ff7f0e',
            'LTU': '#2ca02c',
            'LUX': '#2ca02c',
            'LVA': '#2ca02c',
            'MAC': '#9467bd',
            'MAF': '#e377c2',
            'MAR': '#ff7f0e',
            'MCO': '#2ca02c',
            'MDA': '#2ca02c',
            'MDG': '#ff7f0e',
            'MDV': '#9467bd',
            'MEX': '#6baed6',
            'MHL': '#8c564b',
            'MKD': '#2ca02c',
            'MLI': '#ff7f0e',
            'MLT': '#2ca02c',
            'MMR': '#9467bd',
            'MNE': '#2ca02c',
            'MNG': '#9467bd',
            'MNP': '#8c564b',
            'MOZ': '#ff7f0e',
            'MRT': '#ff7f0e',
            'MSR': '#6baed6',
            'MTQ': '#6baed6',
            'MUS': '#ff7f0e',
            'MWI': '#ff7f0e',
            'MYS': '#9467bd',
            'MYT': '#ff7f0e',
            'NAM': '#ff7f0e',
            'NCL': '#8c564b',
            'NER': '#ff7f0e',
            'NFK': '#8c564b',
            'NGA': '#ff7f0e',
            'NIC': '#6baed6',
            'NIU': '#8c564b',
            'NLD': '#2ca02c',
            'NOR': '#2ca02c',
            'NPL': '#9467bd',
            'NRU': '#8c564b',
            'NZL': '#8c564b',
            'OMN': '#9467bd',
            'PAK': '#9467bd',
            'PAN': '#6baed6',
            'PCN': '#8c564b',
            'PER': '#e377c2',
            'PHL': '#9467bd',
            'PLW': '#8c564b',
            'PNG': '#8c564b',
            'POL': '#2ca02c',
            'PRI': '#6baed6',
            'PRK': '#9467bd',
            'PRT': '#2ca02c',
            'PRY': '#e377c2',
            'PSE': '#9467bd',
            'PYF': '#8c564b',
            'QAT': '#9467bd',
            'REU': '#ff7f0e',
            'ROU': '#2ca02c',
            'RUS': '#2ca02c',
            'RWA': '#ff7f0e',
            'SAU': '#9467bd',
            'SDN': '#ff7f0e',
            'SEN': '#ff7f0e',
            'SGP': '#9467bd',
            'SGS': '#d62728',
            'SHN': '#ff7f0e',
            'SJM': '#2ca02c',
            'SLB': '#8c564b',
            'SLE': '#ff7f0e',
            'SLV': '#6baed6',
            'SMR': '#2ca02c',
            'SOM': '#ff7f0e',
            'SPM': '#6baed6',
            'SRB': '#2ca02c',
            'SSD': '#ff7f0e',
            'STP': '#ff7f0e',
            'SUR': '#e377c2',
            'SVK': '#2ca02c',
            'SVN': '#2ca02c',
            'SWE': '#2ca02c',
            'SWZ': '#ff7f0e',
            'SXM': '#e377c2',
            'SYC': '#ff7f0e',
            'SYR': '#9467bd',
            'TCA': '#6baed6',
            'TCD': '#ff7f0e',
            'TGO': '#ff7f0e',
            'THA': '#9467bd',
            'TJK': '#9467bd',
            'TKL': '#8c564b',
            'TKM': '#9467bd',
            'TLS': '#9467bd',
            'TON': '#8c564b',
            'TTO': '#6baed6',
            'TUN': '#ff7f0e',
            'TUR': '#2ca02c',
            'TUV': '#8c564b',
            'TWN': '#9467bd',
            'TZA': '#ff7f0e',
            'UGA': '#ff7f0e',
            'UKR': '#2ca02c',
            'UMI': '#8c564b',
            'URY': '#e377c2',
            'USA': '#6baed6',
            'UZB': '#9467bd',
            'VAT': '#2ca02c',
            'VCT': '#6baed6',
            'VEN': '#e377c2',
            'VGB': '#6baed6',
            'VIR': '#6baed6',
            'VNM': '#9467bd',
            'VUT': '#8c564b',
            'WLF': '#8c564b',
            'WSM': '#8c564b',
            'YEM': '#9467bd',
            'ZAF': '#ff7f0e',
            'ZMB': '#ff7f0e',
            'ZWE': '#ff7f0e',
            'BUBBLE': '#FC8D59',
			 defaultFill: '#ffc9e6'
           //  defaultFill: '#ff7f0e'
         },
        data: {
            'ABW': {fillKey: 'ABW'},
            'AFG': {fillKey: 'AFG'},
            'AGO': {fillKey: 'AGO'},
            'AIA': {fillKey: 'AIA'},
            'ALA': {fillKey: 'ALA'},
            'ALB': {fillKey: 'ALB'},
            'AND': {fillKey: 'AND'},
            'ARE': {fillKey: 'ARE'},
            'ARG': {fillKey: 'ARG'},
            'ARM': {fillKey: 'ARM'},
            'ASM': {fillKey: 'ASM'},
            'ATA': {fillKey: 'ATA'},
            'ATF': {fillKey: 'ATF'},
            'ATG': {fillKey: 'ATG'},
            'AUS': {fillKey: 'AUS'},
            'AUT': {fillKey: 'AUT'},
            'AZE': {fillKey: 'AZE'},
            'BDI': {fillKey: 'BDI'},
            'BEL': {fillKey: 'BEL'},
            'BEN': {fillKey: 'BEN'},
            'BES': {fillKey: 'BES'},
            'BFA': {fillKey: 'BFA'},
            'BGD': {fillKey: 'BGD'},
            'BGR': {fillKey: 'BGR'},
            'BHR': {fillKey: 'BHR'},
            'BHS': {fillKey: 'BHS'},
            'BIH': {fillKey: 'BIH'},
            'BLM': {fillKey: 'BLM'},
            'BLR': {fillKey: 'BLR'},
            'BLZ': {fillKey: 'BLZ'},
            'BMU': {fillKey: 'BMU'},
            'BOL': {fillKey: 'BOL'},
            'BRA': {fillKey: 'BRA'},
            'BRB': {fillKey: 'BRB'},
            'BRN': {fillKey: 'BRN'},
            'BTN': {fillKey: 'BTN'},
            'BVT': {fillKey: 'BVT'},
            'BWA': {fillKey: 'BWA'},
            'CAF': {fillKey: 'CAF'},
            'CAN': {fillKey: 'CAN'},
            'CCK': {fillKey: 'CCK'},
            'CHE': {fillKey: 'CHE'},
            'CHL': {fillKey: 'CHL'},
            'CHN': {fillKey: 'CHN'},
            'CIV': {fillKey: 'CIV'},
            'CMR': {fillKey: 'CMR'},
            'COD': {fillKey: 'COD'},
            'COG': {fillKey: 'COG'},
            'COK': {fillKey: 'COK'},
            'COL': {fillKey: 'COL'},
            'COM': {fillKey: 'COM'},
            'CPV': {fillKey: 'CPV'},
            'CRI': {fillKey: 'CRI'},
            'CUB': {fillKey: 'CUB'},
            'CUW': {fillKey: 'CUW'},
            'CXR': {fillKey: 'CXR'},
            'CYM': {fillKey: 'CYM'},
            'CYP': {fillKey: 'CYP'},
            'CZE': {fillKey: 'CZE'},
            'DEU': {fillKey: 'DEU'},
            'DJI': {fillKey: 'DJI'},
            'DMA': {fillKey: 'DMA'},
            'DNK': {fillKey: 'DNK'},
            'DOM': {fillKey: 'DOM'},
            'DZA': {fillKey: 'DZA'},
            'ECU': {fillKey: 'ECU'},
            'EGY': {fillKey: 'EGY'},
            'ERI': {fillKey: 'ERI'},
            'ESH': {fillKey: 'ESH'},
            'ESP': {fillKey: 'ESP'},
            'EST': {fillKey: 'EST'},
            'ETH': {fillKey: 'ETH'},
            'FIN': {fillKey: 'FIN'},
            'FJI': {fillKey: 'FJI'},
            'FLK': {fillKey: 'FLK'},
            'FRA': {fillKey: 'FRA'},
            'FRO': {fillKey: 'FRO'},
            'FSM': {fillKey: 'FSM'},
            'GAB': {fillKey: 'GAB'},
            'GBR': {fillKey: 'GBR'},
            'GEO': {fillKey: 'GEO'},
            'GGY': {fillKey: 'GGY'},
            'GHA': {fillKey: 'GHA'},
            'GIB': {fillKey: 'GIB'},
            'GIN': {fillKey: 'GIN'},
            'GLP': {fillKey: 'GLP'},
            'GMB': {fillKey: 'GMB'},
            'GNB': {fillKey: 'GNB'},
            'GNQ': {fillKey: 'GNQ'},
            'GRC': {fillKey: 'GRC'},
            'GRD': {fillKey: 'GRD'},
            'GRL': {fillKey: 'GRL'},
            'GTM': {fillKey: 'GTM'},
            'GUF': {fillKey: 'GUF'},
            'GUM': {fillKey: 'GUM'},
            'GUY': {fillKey: 'GUY'},
            'HKG': {fillKey: 'HKG'},
            'HMD': {fillKey: 'HMD'},
            'HND': {fillKey: 'HND'},
            'HRV': {fillKey: 'HRV'},
            'HTI': {fillKey: 'HTI'},
            'HUN': {fillKey: 'HUN'},
            'IDN': {fillKey: 'IDN'},
            'IMN': {fillKey: 'IMN'},
            'IND': {fillKey: 'IND'},
            'IOT': {fillKey: 'IOT'},
            'IRL': {fillKey: 'IRL'},
            'IRN': {fillKey: 'IRN'},
            'IRQ': {fillKey: 'IRQ'},
            'ISL': {fillKey: 'ISL'},
            'ISR': {fillKey: 'ISR'},
            'ITA': {fillKey: 'ITA'},
            'JAM': {fillKey: 'JAM'},
            'JEY': {fillKey: 'JEY'},
            'JOR': {fillKey: 'JOR'},
            'JPN': {fillKey: 'JPN'},
            'KAZ': {fillKey: 'KAZ'},
            'KEN': {fillKey: 'KEN'},
            'KGZ': {fillKey: 'KGZ'},
            'KHM': {fillKey: 'KHM'},
            'KIR': {fillKey: 'KIR'},
            'KNA': {fillKey: 'KNA'},
            'KOR': {fillKey: 'KOR'},
            'KWT': {fillKey: 'KWT'},
            'LAO': {fillKey: 'LAO'},
            'LBN': {fillKey: 'LBN'},
            'LBR': {fillKey: 'LBR'},
            'LBY': {fillKey: 'LBY'},
            'LCA': {fillKey: 'LCA'},
            'LIE': {fillKey: 'LIE'},
            'LKA': {fillKey: 'LKA'},
            'LSO': {fillKey: 'LSO'},
            'LTU': {fillKey: 'LTU'},
            'LUX': {fillKey: 'LUX'},
            'LVA': {fillKey: 'LVA'},
            'MAC': {fillKey: 'MAC'},
            'MAF': {fillKey: 'MAF'},
            'MAR': {fillKey: 'MAR'},
            'MCO': {fillKey: 'MCO'},
            'MDA': {fillKey: 'MDA'},
            'MDG': {fillKey: 'MDG'},
            'MDV': {fillKey: 'MDV'},
            'MEX': {fillKey: 'MEX'},
            'MHL': {fillKey: 'MHL'},
            'MKD': {fillKey: 'MKD'},
            'MLI': {fillKey: 'MLI'},
            'MLT': {fillKey: 'MLT'},
            'MMR': {fillKey: 'MMR'},
            'MNE': {fillKey: 'MNE'},
            'MNG': {fillKey: 'MNG'},
            'MNP': {fillKey: 'MNP'},
            'MOZ': {fillKey: 'MOZ'},
            'MRT': {fillKey: 'MRT'},
            'MSR': {fillKey: 'MSR'},
            'MTQ': {fillKey: 'MTQ'},
            'MUS': {fillKey: 'MUS'},
            'MWI': {fillKey: 'MWI'},
            'MYS': {fillKey: 'MYS'},
            'MYT': {fillKey: 'MYT'},
            'NAM': {fillKey: 'NAM'},
            'NCL': {fillKey: 'NCL'},
            'NER': {fillKey: 'NER'},
            'NFK': {fillKey: 'NFK'},
            'NGA': {fillKey: 'NGA'},
            'NIC': {fillKey: 'NIC'},
            'NIU': {fillKey: 'NIU'},
            'NLD': {fillKey: 'NLD'},
            'NOR': {fillKey: 'NOR'},
            'NPL': {fillKey: 'NPL'},
            'NRU': {fillKey: 'NRU'},
            'NZL': {fillKey: 'NZL'},
            'OMN': {fillKey: 'OMN'},
            'PAK': {fillKey: 'PAK'},
            'PAN': {fillKey: 'PAN'},
            'PCN': {fillKey: 'PCN'},
            'PER': {fillKey: 'PER'},
            'PHL': {fillKey: 'PHL'},
            'PLW': {fillKey: 'PLW'},
            'PNG': {fillKey: 'PNG'},
            'POL': {fillKey: 'POL'},
            'PRI': {fillKey: 'PRI'},
            'PRK': {fillKey: 'PRK'},
            'PRT': {fillKey: 'PRT'},
            'PRY': {fillKey: 'PRY'},
            'PSE': {fillKey: 'PSE'},
            'PYF': {fillKey: 'PYF'},
            'QAT': {fillKey: 'QAT'},
            'REU': {fillKey: 'REU'},
            'ROU': {fillKey: 'ROU'},
            'RUS': {fillKey: 'RUS'},
            'RWA': {fillKey: 'RWA'},
            'SAU': {fillKey: 'SAU'},
            'SDN': {fillKey: 'SDN'},
            'SEN': {fillKey: 'SEN'},
            'SGP': {fillKey: 'SGP'},
            'SGS': {fillKey: 'SGS'},
            'SHN': {fillKey: 'SHN'},
            'SJM': {fillKey: 'SJM'},
            'SLB': {fillKey: 'SLB'},
            'SLE': {fillKey: 'SLE'},
            'SLV': {fillKey: 'SLV'},
            'SMR': {fillKey: 'SMR'},
            'SOM': {fillKey: 'SOM'},
            'SPM': {fillKey: 'SPM'},
            'SRB': {fillKey: 'SRB'},
            'SSD': {fillKey: 'SSD'},
            'STP': {fillKey: 'STP'},
            'SUR': {fillKey: 'SUR'},
            'SVK': {fillKey: 'SVK'},
            'SVN': {fillKey: 'SVN'},
            'SWE': {fillKey: 'SWE'},
            'SWZ': {fillKey: 'SWZ'},
            'SXM': {fillKey: 'SXM'},
            'SYC': {fillKey: 'SYC'},
            'SYR': {fillKey: 'SYR'},
            'TCA': {fillKey: 'TCA'},
            'TCD': {fillKey: 'TCD'},
            'TGO': {fillKey: 'TGO'},
            'THA': {fillKey: 'THA'},
            'TJK': {fillKey: 'TJK'},
            'TKL': {fillKey: 'TKL'},
            'TKM': {fillKey: 'TKM'},
            'TLS': {fillKey: 'TLS'},
            'TON': {fillKey: 'TON'},
            'TTO': {fillKey: 'TTO'},
            'TUN': {fillKey: 'TUN'},
            'TUR': {fillKey: 'TUR'},
            'TUV': {fillKey: 'TUV'},
            'TWN': {fillKey: 'TWN'},
            'TZA': {fillKey: 'TZA'},
            'UGA': {fillKey: 'UGA'},
            'UKR': {fillKey: 'UKR'},
            'UMI': {fillKey: 'UMI'},
            'URY': {fillKey: 'URY'},
            'USA': {fillKey: 'USA'},
            'UZB': {fillKey: 'UZB'},
            'VAT': {fillKey: 'VAT'},
            'VCT': {fillKey: 'VCT'},
            'VEN': {fillKey: 'VEN'},
            'VGB': {fillKey: 'VGB'},
            'VIR': {fillKey: 'VIR'},
            'VNM': {fillKey: 'VNM'},
            'VUT': {fillKey: 'VUT'},
            'WLF': {fillKey: 'WLF'},
            'WSM': {fillKey: 'WSM'},
            'YEM': {fillKey: 'YEM'},
            'ZAF': {fillKey: 'ZAF'},
            'ZMB': {fillKey: 'ZMB'},
            'ZWE': {fillKey: 'ZWE'},
            'BUBBLE': {fillKey: 'BUBBLE'}
         }
        
        
    });
     var bombs = [{
        name: 'North America',
        radius: 48,
        ee:33,
		ar:5,
		arch:3,
		mech:3,
		se:3,
		eneser:1,
		elec:0,
        latitude: 50.09,
        longitude: 265.71,
		fillOpacity:0.8,
		borderColor:"#fc5858"
      },{
        name: 'Europe',
        radius: 13,
        ee:5,
		ar:7,
		arch:0,
		mech:1,
		se:0,
		eneser:0,
		elec:0,
        latitude: 53.482,
        longitude: 24.5854,
		fillOpacity:0.8,
		borderColor:"#fc5858"
      },{
        name: 'South America',
        radius: 2,
        ee:1,
		ar:1,
		arch:0,
		mech:0,
		se:0,
		eneser:0,
		elec:0,
        latitude: -13.09,
        longitude: 295.71,
		fillOpacity:0.8,
		borderColor:"#fc5858"
      },{
        name: 'Asia',
        radius: 4,
        ee:3,
		ar:0,
		arch:0,
		mech:0,
		se:0,
		eneser:0,
		elec:1,
        latitude: 37.482,
        longitude: 94.5854,
		fillOpacity:0.8,
		borderColor:"#fc5858"
      },{
        name: 'Oceania',
        radius: 3,
        ee:2,
		ar:1,
		arch:0,
		mech:0,
		se:0,
		eneser:0,
		elec:0,
        latitude: -23,
        longitude: 125, //134.5854,
		fillOpacity:0.8,
		borderColor:"#fc5858"
      }
    ];

     
map.bubbles(bombs, {
    popupTemplate: function (geo, data) {
            return ['<div class="hoverinfo"><strong>' +  data.name + ' (' + data.radius+ ' participants)' ,
            '<br/>Energy modeler/ Energy Analyst:: ' +  data.ee + '',
            '<br/>Academic professional / Research Engineer: ' +  data.ar + '',
			'<br/>Architect: ' +  data.arch + '',
			'<br/>Mechanical engineer: ' +  data.mech + '',
			'<br/>Software developer: ' +  data.se + '',
			'<br/>Energy services / mechanical contractor: ' +  data.eneser + '',
			'<br/>Electrical engineer: : ' +  data.elec + '',
            '</strong></div>'].join('');
    },
    popupOnHover: true,
    highlightOnHover: false,
    

});
}